language: node_js
node_js:
- '8'
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
- yarn lint
- TZ="America/Los_Angeles" yarn test
after_success: yarn run coverage
env:
  global:
    secure: I3R2N1E1UWEzfxadsgmbvLX9555NWoPeUHZ06BF7o+e6KUEAsP4go78v8wyKi93sOP+giyZJycWGlJNqq1HPuXIEkk2yp1HD8m9p5pTkFJszjNz33mcbNjvvKO5h68/apoJ8lGMX9Oh9L5RLUcfKRMQLuDyZOLKWeI/mYenJcFgxhxJxOt1ilW4VuDMsUQ8HgXDv3zYacmgyVHbZIG+sJ0OBxKPslLITINY4D88VA6kQBk6PMpghGh8fATMuE3ytqXDK0lQexxR2YDb/jLN9ikMPO7kjQAR/JyYbG1t0Rt2PCgDCmPkDrINDSTczT3Bx36Vbf3ikHThlGk93NucgdZqHYllpdmyqgeGMgYZzjzFRrAN+Gpi/iqV+zMYvb9bYh/5VRx5QbCR9OrfHXxCdSckxMUwiaUdPNEvUUPBvblwdWB+4iMn2OUAmMUN7Bm1XFNmDBkjJgBF/HeGYZLoglyh5MfmfGk1VBJMg527MingS81KZ3/Spv0ZDT8fETwm+k0kNqogBhLA7lrvJldgtzq0yKojbhrWaA6GPGOezS/AZHAVn4BNBNq+h/PJFWS2cOXqorphUZhOVv9bJJM9SnSF8wThsbQEgrajfE1H3pFewDHEMpJ0d7FJ5ka12FGQUoalU6HI2mMVl1R83BW5PwQfsLSUIkjntfPCM18r+VO0=
